PY_LGPIO/lgpio.i: Replace undefined functions
Replace functions PyInt_Check, PyInt_AsLong, PyInt_FromLong and
PyString_FromString for Python3 because SWIG dropped its Python
2/3 compat shim in version 4.1. Fixes:

error: implicit declaration of function 'PyInt_FromLong';
did you mean 'PyLong_FromLong'? [-Wimplicit-function-declaration]

error: implicit declaration of function 'PyInt_Check';
did you mean 'PySet_Check'? [-Wimplicit-function-declaration]

error: implicit declaration of function 'PyInt_AsLong';
did you mean 'PyLong_AsLong'? [-Wimplicit-function-declaration]

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>